### ISSUE TITLE
data preparation for semantic_kitti

### ISSUE THREAD

**Issue by songw-zju** [tsunghan-mama/ReDAL#1]
Hi, thanks for your great work!

I'm getting errors when trying to prepare data for semantickitti in Step 3(Calculate point cloud properties). `gen_surface_variation.py` only contains opreations for S3DIS. When I modify the dataset setting for semantic_kitti,  I get the following error
```
Traceback (most recent call last):
  File "gen_surface_variation.py", line 58, in <module>
    for fname in os.listdir(coords_dir):
FileNotFoundError: [Errno 2] No such file or directory: '/data/semantic_kitti/dataset/sequences/00/coords'
```

**Comment by tsunghan-wu** [comment]
Great catching!

It is indeed a bug. However, it is easy to fix this bug by modifying the corresponding subdirectory name, i.e., "coords" --> "velodyne".
Since I am busy these days, I might fix this bug and push a revised version next week.
Again, thanks for pointing out this issue.

Best,
Tsung-Han Wu

**Comment by songw-zju** [comment]
> Great catching!
> 
> It is indeed a bug. However, it is easy to fix this bug by modifying the corresponding subdirectory name, i.e., "coords" --> "velodyne". Since I am busy these days, I might fix this bug and push a revised version next week. Again, thanks for pointing out this issue.
> 
> Best, Tsung-Han Wu

Thanks for your response. After modifying the corresponding subdirectory name, there are still some bugs as 'gen_surface_variation.py' mainly contains opreations for S3DIS. Thanks for your great work again and looking forward your update.

**Comment by tsunghan-wu** [comment]
Hi,

Sorry for the late reply. I have modified the code for the SemanticKITTI data preparation.
You can pull the updated version and run the code.
Thanks.

**Comment by tsunghan-wu** [comment]
Close for long inactivity.
