### ISSUE TITLE
About config file

### ISSUE THREAD

**Issue by iris0329** [tsunghan-mama/ReDAL#3]
Hi, thanks for opening source this brilliant work.

But it seems you miss the ReDAL config file. Could you provide that?

Many thanks~

**Comment by tsunghan-wu** [comment]
Hi,

The config files are left in the `active_selection` directory. Specifically, there are three config files (`ReDAL_S3DIS.config`, `ReDAL_Scannetv2.config` and `ReDAL_SemanticKITTI.config`)  for three different datasets.

Hope this message helps.

Best,
Tsung-Han Wu

**Comment by iris0329** [comment]
Thank you Tsung-Han, it helps~
