### ISSUE TITLE
Image segmentation 

### ISSUE THREAD

**Issue by abhigoku10** [tsunghan-mama/ReDAL#4]
@tsunghan-mama  hi thanks for sharing this wonderful code base i had few queries 

1. Does this source code support or can be user for point cloud data lidar for automotive driving scenario 
2. Does this source code also support 2d image segmentation 
Thanks in advance

**Comment by tsunghan-wu** [comment]
Hi,

1. Yes. This code is applicable to self-driving scenario as well as indoor robotics. Specifically, the code supports SemanticKITTI dataset (outdoor scene) and S3DIS dataset (indoor room).
2. Yes. This method can also be used on 2D image segmentation. In fact, we did further experiments on the 2D dataset few month ago and found that region-based selection **highly** reduces the annotation burden. (You can refer to [thin link](https://arxiv.org/abs/2202.06484) to see how the approach can be used in 2D.)

Hope these information help.

Best,
Tsung-Han

**Comment by tsunghan-wu** [comment]
Close the issue due to inactivity for a long time.
