### ISSUE TITLE
The miou result in S3DIS

### ISSUE THREAD

**Issue by DpDark** [tsunghan-mama/ReDAL#8]
Hi, I run ReDAL in S3DIS, but no matter how many times I try, I can't reproduce the results in the paper, for the best I reproduce, it can only get 38.2/5%, 43.2/7%,45.5/%9,48.9/%11, much lower than the paper show. On the other hand, the results of the experiment seem to be very unstable, and the fluctuation of the results of each experiment is very large, about 2%~3%

I try it on two RTX3090(24GB) and the experiment settings are same as the paper(the code default setting). I see others in issue#5 said they can reproduce the result on two GPUs (V5000) with 24GB, so I don't doubt the authenticity of the experimental results.

One reason I guess is that the division of superpoints is not stable, leading to different experimental results, but I have not been able to obtain superpoints that can achieve the performance presented in the paper. Or do you have any other suggestions to reproduce your model performance?

**Comment by tsunghan-wu** [comment]
Hi,

I agree that the randomness of the region division process could affect the results, but I believed that obtaining only 48.9 mIoU with 11% labeled points is unusual (even lower than random region selection referred to Fig. 8 of the main paper). Have you checked if you have set the correct configuration or if there could be any other issues? Unfortunately, without more details about your implementation, I can't provide more specific suggestions.

**Comment by DpDark** [comment]
Hi wu，
I fully use the default settings in the code to ensure the setting consistency with the paper. The performance mentioned above is implemented on SPVCNN. For the **random** performance in S3DIS by SPVCNN, it can get higher miou than the performance presented in Fig.5 and the gap between random and ReDAL is only about 3%~5%, that's very strange. So I still doubt that it is the problem of super-point division？ So if it is feasible, can you share the data of super-point? I will continue to verify this issue and thank you for your answer.
